### ISSUE TITLE
M1 support using CocoaPods

### ISSUE THREAD

**Issue by mmiedlarz** [applanga/sdk-ios#13]
Hi there!

I'm integrating Applanga SDK to iOS project (which is developed both on M1 and Intel Macbooks), 
and looks like it's not fully compatible with it. After installation I see that `arm` is added to pods excluded archs on CocoaPods settings and it fails to build. 

Are there any plans to change build settings or podspec to support it fully?

**Comment by steffen-roemer** [comment]
Hi @mmiedlarz,

yes we're working on that. M1 support with with cooapods should be working if you build for device but not for simulator due to conflicting architecture. The way to resolve that is by using a universal .xcframework instead of normal .framework but that for some reason we're still investigating, is not working properly with cocoapods at the moment. We provide a .xcframework via swift package manager and that should be working fine on m1 but I'll let you know once we resolved the cocoapods issue as well.

best regards,

Steffen

**Comment by mmiedlarz** [comment]
Hi @steffen-roemer,

Thanks for the reply. So far we're using physical devices to build our app on M1, but it's getting cumbersome as more team members are switching to M1. 
Is the .xcframework available for download anywhere? I'd like to try include it as a binary in our code to avoid adding SPM.

Best,
Michal

**Comment by steffen-roemer** [comment]
Hi @mmiedlarz 

its in this repo https://github.com/applanga/sdk-ios/tree/master/Applanga.xcframework

Best,
Steffen

**Comment by mmiedlarz** [comment]
Thanks! I'll try to use it in our project.

**Comment by steffen-roemer** [comment]
Hi @mmiedlarz ,

this should now be resolved with the latest SDK update.

thank you for the patience,
Steffen
